"""Phase 1 — empirical lexicon optimizer.

For every English word in the current LEXICON, pick the encoding that
minimizes BPE token count (with tiktoken's o200k_base as proxy for
Claude). Candidates: the English word itself, the current Glyph stem,
and a small set of short ASCII alternatives. Tie-breaker: fewer
characters; then prefer the form whose decoder mapping is unambiguous.

Outputs:
  - tools/optimized_lexicon.py — drop-in replacement LEXICON dict
  - tools/lexicon_diff.json    — per-entry before/after with token deltas
  - prints summary to stdout

The decoder direction will continue to accept the old stems (decoder
backwards-compat is enforced separately in ai_language.py), so this
optimizer only changes the encoder's choice of stem.
"""
from __future__ import annotations

import json
import sys
from collections import defaultdict
from pathlib import Path

import tiktoken

sys.path.insert(0, str(Path(__file__).parent.parent))
from chimeralang_mcp.ai_language import LEXICON, OPERATORS  # noqa: E402

ENC = tiktoken.get_encoding("o200k_base")


def n_tokens(s: str) -> int:
    # Whitespace-prefixed: that's how words appear mid-sentence in BPE.
    return len(ENC.encode(" " + s)) if s else 0


# Operator glyphs map English connectives to their (potentially multi-token)
# Unicode symbols. Replacing them with English words is part of the
# tokenizer-awareness rebuild.
OPERATOR_REPLACEMENTS: dict[str, str] = {
    "→": "to",          # was "leads to" — used as preposition glyph
    "⇒": "then",        # therefore / then
    "∧": "and",
    "∨": "or",
    "¬": "not",
    "≈": "about",
    "≠": "not_eq",
    "≡": "eq",
    "∃": "some",
    "∀": "all",
    "∅": "none",
    "←": "because",
}


def best_glyph_for(eng: str, current: str) -> tuple[str, str, int, int]:
    """Return (chosen, source, tokens_chosen, tokens_current)."""
    # Empty-string mappings (articles, auxiliaries dropped) stay empty —
    # dropping is always a win.
    if current == "":
        return "", "drop_unchanged", 0, 0

    # If the current glyph is an operator, prefer the English replacement.
    if current in OPERATOR_REPLACEMENTS:
        candidate = OPERATOR_REPLACEMENTS[current]
        cand_tok = n_tokens(candidate)
        cur_tok = n_tokens(current)
        # Operators stay if they're cheaper (some 1-token Unicode survives BPE).
        if cur_tok <= cand_tok:
            return current, "operator_kept", cur_tok, cur_tok
        return candidate, "operator_replaced", cand_tok, cur_tok

    # Tense-suffix forms ("fix^", "wnt^") were the worst offenders in the spike.
    # Replace with the actual English past-tense form.
    if current.endswith(("^", "~")):
        # eng is already the right English form for tense (e.g., "fixed", "going")
        candidate = eng
        cand_tok = n_tokens(candidate)
        cur_tok = n_tokens(current)
        if cand_tok < cur_tok:
            return candidate, "tense_suffix_dropped", cand_tok, cur_tok
        return current, "tense_suffix_kept", cur_tok, cur_tok

    # General case: English word vs. current stem.
    eng_tok = n_tokens(eng)
    cur_tok = n_tokens(current)
    if cur_tok < eng_tok:
        return current, "stem_kept", cur_tok, eng_tok
    if eng_tok < cur_tok:
        return eng, "english_preferred", eng_tok, cur_tok
    # Tied on tokens. Prefer the SHORTER form for char savings (still a win
    # for human display + log volume), but only if the shorter form is the
    # current stem — switching from a stem to English when both are 1 token
    # makes Glyph more readable, which we value at a tie.
    if len(current) < len(eng):
        return current, "stem_kept_tie", cur_tok, cur_tok
    return eng, "english_tie", eng_tok, eng_tok


def main() -> None:
    new_lexicon: dict[str, str] = {}
    diffs: list[dict] = []
    by_source: dict[str, int] = defaultdict(int)
    total_tokens_before = 0
    total_tokens_after = 0

    for eng, glyph in LEXICON.items():
        chosen, source, tok_after, tok_before = best_glyph_for(eng, glyph)
        new_lexicon[eng] = chosen
        diffs.append({
            "english": eng,
            "old_glyph": glyph,
            "new_glyph": chosen,
            "tokens_before": tok_before,
            "tokens_after": tok_after,
            "source": source,
            "changed": chosen != glyph,
        })
        by_source[source] += 1
        total_tokens_before += tok_before
        total_tokens_after += tok_after

    # Write the optimized lexicon as a Python module. The output is a
    # straight literal — easy to diff, easy to inline into ai_language.py.
    out_lex = Path(__file__).parent / "optimized_lexicon.py"
    with out_lex.open("w") as f:
        f.write('"""Auto-generated by tools/optimize_lexicon.py — do not edit by hand.\n\n')
        f.write("Empirically optimized Glyph LEXICON aligned with tiktoken o200k_base\n")
        f.write("(Claude-equivalent BPE). Re-run the optimizer to regenerate after any\n")
        f.write('LEXICON change."""\n\n')
        f.write("LEXICON: dict[str, str] = {\n")
        for eng, glyph in new_lexicon.items():
            # Use repr() to handle Unicode and quotes safely.
            f.write(f"    {eng!r}: {glyph!r},\n")
        f.write("}\n")

    out_diff = Path(__file__).parent / "lexicon_diff.json"
    out_diff.write_text(json.dumps({
        "tokenizer": "tiktoken o200k_base",
        "n_entries": len(LEXICON),
        "n_changed": sum(1 for d in diffs if d["changed"]),
        "tokens_before_sum": total_tokens_before,
        "tokens_after_sum": total_tokens_after,
        "sum_pct_saved": round(100 * (total_tokens_before - total_tokens_after)
                               / max(1, total_tokens_before), 1),
        "by_source": dict(by_source),
        "diffs": diffs,
    }, indent=2))

    print("=" * 72)
    print("LEXICON OPTIMIZATION RESULTS")
    print("=" * 72)
    print(f"  Entries processed:        {len(LEXICON)}")
    print(f"  Entries changed:          {sum(1 for d in diffs if d['changed'])}")
    print(f"  Sum of tokens (before):   {total_tokens_before}")
    print(f"  Sum of tokens (after):    {total_tokens_after}")
    print(f"  Sum-level reduction:      "
          f"{round(100 * (total_tokens_before - total_tokens_after) / max(1, total_tokens_before), 1)}%")
    print()
    print("  By source:")
    for source, count in sorted(by_source.items(), key=lambda kv: -kv[1]):
        print(f"    {source:<28} {count:>4}")
    print()
    print(f"  Output: {out_lex}")
    print(f"  Output: {out_diff}")


if __name__ == "__main__":
    main()
